all: 
	clang -o question01 question01.c 
	clang -o question02 question02.c 
	clang -o question03 question03.c 
	clang -o question04 question04.c -Wall
	clang -o question05 question05.c -Wall
	clang -o question06 question06.c -Wall
	clang -o question07 question07.c -Wall
	clang -o question08 question08.c -Wall